In [42]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder, OneHotEncoder
import pickle
from tensorflow.keras.callbacks import EarlyStopping, TensorBoard
import datetime

In [22]:
data = pd.read_csv("Churn_Modelling.csv")
data.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [23]:
data = data.drop(['RowNumber', 'CustomerId', 'Surname'], axis=1)

In [24]:
## Encode categorical variable

label_encode_gender = LabelEncoder()
data['Gender'] = label_encode_gender.fit_transform(data['Gender'])

In [25]:
ohe_geo = OneHotEncoder(handle_unknown="ignore")

geo_encoder = ohe_geo.fit_transform(data[['Geography']]).toarray()
geo_en_df = pd.DataFrame(geo_encoder, columns=ohe_geo.get_feature_names_out(['Geography']))

geo_en_df

      Geography_France  Geography_Germany  Geography_Spain
0                  1.0                0.0              0.0
1                  0.0                0.0              1.0
2                  1.0                0.0              0.0
3                  1.0                0.0              0.0
4                  0.0                0.0              1.0
...                ...                ...              ...
9995               1.0                0.0              0.0
9996               1.0                0.0              0.0
9997               1.0                0.0              0.0
9998               0.0                1.0              0.0
9999               1.0                0.0              0.0

[10000 rows x 3 columns]

In [26]:
data = pd.concat([data.drop('Geography', axis=1), geo_en_df], axis=1)
data.head()

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0

In [27]:
X = data.drop('EstimatedSalary', axis=1)
Y = data['EstimatedSalary']

In [29]:

# load the encoder & scaler
with open('ohe_geo.pkl', 'rb') as file:
    ohe_geo=pickle.load(file)


with open('label_encode_gender.pkl', 'rb') as file:
    label_encode_gender=pickle.load(file)


with open('scaler.pkl', 'rb') as file:
    scaler=pickle.load(file)

In [30]:
# Split in training and testing
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=42)

# Scale the features
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

## ANN Regression Problem Statement

In [31]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [36]:
# Model building

model = Sequential([
    Dense(64, activation='relu', input_shape=(X_train.shape[1],)),
    Dense(32, activation='relu'),
    Dense(1) # when no activation fn is taken, then default act. fn. is Linear Act. Fn.
])

model.compile(optimizer='adam', loss='mean_absolute_error', metrics='mae')
model.summary()

Model: "sequential_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_9 (Dense)             (None, 64)                832

 dense_10 (Dense)            (None, 32)                2080

 dense_11 (Dense)            (None, 1)                 33

=================================================================
Total params: 2945 (11.50 KB)
Trainable params: 2945 (11.50 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [43]:
# Set up the Tensorboard

log_dir = "regressionlogs/fit/" + datetime.datetime.now().strftime("%Y%m%d - %H%M%S")
tensorflow_callback = TensorBoard(log_dir=log_dir, histogram_freq=1)

In [44]:
early_stopping_callback = EarlyStopping(monitor='val_loss', patience=10, restore_best_weights=True)

In [45]:
history = model.fit(
    X_train, Y_train, validation_data = (X_test, Y_test), epochs = 100,
    callbacks = [tensorflow_callback, early_stopping_callback]
)

Epoch 1/100
WARNING:tensorflow:From c:\Users\harsh\anaconda3\envs\v_env\Lib\site-packages\keras\src\utils\tf_utils.py:492: The name tf.ragged.RaggedTensorValue is deprecated. Please use tf.compat.v1.ragged.RaggedTensorValue instead.

WARNING:tensorflow:From c:\Users\harsh\anaconda3\envs\v_env\Lib\site-packages\keras\src\engine\base_layer_utils.py:384: The name tf.executing_eagerly_outside_functions is deprecated. Please use tf.compat.v1.executing_eagerly_outside_functions instead.

250/250 [==============================] - 8s 15ms/step - loss: 100386.8828 - mae: 100386.8828 - val_loss: 98549.4766 - val_mae: 98549.4766
Epoch 2/100
250/250 [==============================] - 2s 10ms/step - loss: 99744.8125 - mae: 99744.8125 - val_loss: 97246.1562 - val_mae: 97246.1562
Epoch 3/100
250/250 [==============================] - 2s 10ms/step - loss: 97423.1172 - mae: 97423.1172 - val_loss: 93781.0469 - val_mae: 93781.0469
Epoch 4/100
250/250 [==============================] - 2s 10ms/step - loss: 92702.3672 - mae: 92702.3672 - val_loss: 87836.0000 - val_mae: 87836.0000
Epoch 5/100
250/250 [==============================] - 2s 9ms/step - loss: 85658.6406 - mae: 85658.6406 - val_loss: 79982.8516 - val_mae: 79982.8516
Epoch 6/100
250/250 [==============================] - 2s 10ms/step - loss: 77140.6797 - mae: 77140.6797 - val_loss: 71413.4062 - val_mae: 71413.4062
Epoch 7/100
250/250 [==============================] - 3s 10ms/step - loss: 68542.1406 - mae: 68542.1406 - val_loss: 63699.1133 - val_mae: 63699.1133
Epoch 8/100
250/250 [==============================] - 2s 6ms/step - loss: 61235.2266 - mae: 61235.2266 - val_loss: 57820.1719 - val_mae: 57820.1719
Epoch 9/100
250/250 [==============================] - 2s 7ms/step - loss: 56059.0117 - mae: 56059.0117 - val_loss: 54083.2422 - val_mae: 54083.2422
Epoch 10/100
250/250 [==============================] - 2s 8ms/step - loss: 52906.2539 - mae: 52906.2539 - val_loss: 52166.2734 - val_mae: 52166.2734
Epoch 11/100
250/250 [==============================] - 2s 8ms/step - loss: 51359.2109 - mae: 51359.2109 - val_loss: 51458.1055 - val_mae: 51458.1055
Epoch 12/100
250/250 [==============================] - 2s 9ms/step - loss: 50734.5742 - mae: 50734.5742 - val_loss: 51212.5078 - val_mae: 51212.5078
Epoch 13/100
250/250 [==============================] - 2s 10ms/step - loss: 50461.5859 - mae: 50461.5859 - val_loss: 51108.6406 - val_mae: 51108.6406
Epoch 14/100
250/250 [==============================] - 3s 10ms/step - loss: 50324.6875 - mae: 50324.6875 - val_loss: 51038.8984 - val_mae: 51038.8984
Epoch 15/100
250/250 [==============================] - 2s 9ms/step - loss: 50238.8164 - mae: 50238.8164 - val_loss: 50981.1992 - val_mae: 50981.1992
Epoch 16/100
250/250 [==============================] - 2s 9ms/step - loss: 50171.3320 - mae: 50171.3320 - val_loss: 50930.8398 - val_mae: 50930.8398
Epoch 17/100
250/250 [==============================] - 3s 11ms/step - loss: 50116.6016 - mae: 50116.6016 - val_loss: 50886.8086 - val_mae: 50886.8086
Epoch 18/100
250/250 [==============================] - 1s 5ms/step - loss: 50066.9453 - mae: 50066.9453 - val_loss: 50845.2422 - val_mae: 50845.2422
Epoch 19/100
250/250 [==============================] - 1s 5ms/step - loss: 50024.7734 - mae: 50024.7734 - val_loss: 50816.9492 - val_mae: 50816.9492
Epoch 20/100
250/250 [==============================] - 1s 5ms/step - loss: 49992.2148 - mae: 49992.2148 - val_loss: 50786.8906 - val_mae: 50786.8906
Epoch 21/100
250/250 [==============================] - 1s 5ms/step - loss: 49954.7578 - mae: 49954.7578 - val_loss: 50752.8047 - val_mae: 50752.8047
Epoch 22/100
250/250 [==============================] - 1s 5ms/step - loss: 49924.3047 - mae: 49924.3047 - val_loss: 50725.3711 - val_mae: 50725.3711
Epoch 23/100
250/250 [==============================] - 1s 5ms/step - loss: 49896.3516 - mae: 49896.3516 - val_loss: 50703.0898 - val_mae: 50703.0898
Epoch 24/100
250/250 [==============================] - 1s 5ms/step - loss: 49871.0430 - mae: 49871.0430 - val_loss: 50686.4141 - val_mae: 50686.4141
Epoch 25/100
250/250 [==============================] - 1s 5ms/step - loss: 49848.0859 - mae: 49848.0859 - val_loss: 50669.8828 - val_mae: 50669.8828
Epoch 26/100
250/250 [==============================] - 1s 5ms/step - loss: 49823.7031 - mae: 49823.7031 - val_loss: 50640.3398 - val_mae: 50640.3398
Epoch 27/100
250/250 [==============================] - 1s 5ms/step - loss: 49802.1523 - mae: 49802.1523 - val_loss: 50629.5977 - val_mae: 50629.5977
Epoch 28/100
250/250 [==============================] - 1s 5ms/step - loss: 49784.6914 - mae: 49784.6914 - val_loss: 50605.0469 - val_mae: 50605.0469
Epoch 29/100
250/250 [==============================] - 1s 5ms/step - loss: 49759.0273 - mae: 49759.0273 - val_loss: 50591.7578 - val_mae: 50591.7578
Epoch 30/100
250/250 [==============================] - 1s 5ms/step - loss: 49740.1289 - mae: 49740.1289 - val_loss: 50576.0352 - val_mae: 50576.0352
Epoch 31/100
250/250 [==============================] - 1s 4ms/step - loss: 49721.4023 - mae: 49721.4023 - val_loss: 50571.4531 - val_mae: 50571.4531
Epoch 32/100
250/250 [==============================] - 2s 8ms/step - loss: 49705.4102 - mae: 49705.4102 - val_loss: 50567.3984 - val_mae: 50567.3984
Epoch 33/100
250/250 [==============================] - 1s 4ms/step - loss: 49692.1758 - mae: 49692.1758 - val_loss: 50553.5781 - val_mae: 50553.5781
Epoch 34/100
250/250 [==============================] - 1s 4ms/step - loss: 49678.8047 - mae: 49678.8047 - val_loss: 50534.2305 - val_mae: 50534.2305
Epoch 35/100
250/250 [==============================] - 1s 4ms/step - loss: 49662.8164 - mae: 49662.8164 - val_loss: 50522.4805 - val_mae: 50522.4805
Epoch 36/100
250/250 [==============================] - 1s 4ms/step - loss: 49650.1367 - mae: 49650.1367 - val_loss: 50523.2148 - val_mae: 50523.2148
Epoch 37/100
250/250 [==============================] - 1s 3ms/step - loss: 49641.4883 - mae: 49641.4883 - val_loss: 50503.1602 - val_mae: 50503.1602
Epoch 38/100
250/250 [==============================] - 1s 3ms/step - loss: 49626.2422 - mae: 49626.2422 - val_loss: 50503.4766 - val_mae: 50503.4766
Epoch 39/100
250/250 [==============================] - 1s 4ms/step - loss: 49614.7148 - mae: 49614.7148 - val_loss: 50499.4844 - val_mae: 50499.4844
Epoch 40/100
250/250 [==============================] - 1s 4ms/step - loss: 49605.4922 - mae: 49605.4922 - val_loss: 50499.7266 - val_mae: 50499.7266
Epoch 41/100
250/250 [==============================] - 1s 4ms/step - loss: 49593.7305 - mae: 49593.7305 - val_loss: 50480.1602 - val_mae: 50480.1602
Epoch 42/100
250/250 [==============================] - 1s 4ms/step - loss: 49585.2188 - mae: 49585.2188 - val_loss: 50473.0547 - val_mae: 50473.0547
Epoch 43/100
250/250 [==============================] - 1s 4ms/step - loss: 49575.9258 - mae: 49575.9258 - val_loss: 50474.7070 - val_mae: 50474.7070
Epoch 44/100
250/250 [==============================] - 1s 4ms/step - loss: 49566.4805 - mae: 49566.4805 - val_loss: 50467.4492 - val_mae: 50467.4492
Epoch 45/100
250/250 [==============================] - 1s 5ms/step - loss: 49559.0273 - mae: 49559.0273 - val_loss: 50474.3477 - val_mae: 50474.3477
Epoch 46/100
250/250 [==============================] - 1s 4ms/step - loss: 49547.7617 - mae: 49547.7617 - val_loss: 50460.9961 - val_mae: 50460.9961
Epoch 47/100
250/250 [==============================] - 1s 4ms/step - loss: 49542.4492 - mae: 49542.4492 - val_loss: 50450.2070 - val_mae: 50450.2070
Epoch 48/100
250/250 [==============================] - 1s 3ms/step - loss: 49537.9961 - mae: 49537.9961 - val_loss: 50458.3945 - val_mae: 50458.3945
Epoch 49/100
250/250 [==============================] - 1s 4ms/step - loss: 49528.0781 - mae: 49528.0781 - val_loss: 50444.0234 - val_mae: 50444.0234
Epoch 50/100
250/250 [==============================] - 1s 3ms/step - loss: 49522.7891 - mae: 49522.7891 - val_loss: 50449.3633 - val_mae: 50449.3633
Epoch 51/100
250/250 [==============================] - 1s 4ms/step - loss: 49517.1172 - mae: 49517.1172 - val_loss: 50441.6992 - val_mae: 50441.6992
Epoch 52/100
250/250 [==============================] - 1s 3ms/step - loss: 49513.8203 - mae: 49513.8203 - val_loss: 50436.3203 - val_mae: 50436.3203
Epoch 53/100
250/250 [==============================] - 1s 4ms/step - loss: 49502.3438 - mae: 49502.3438 - val_loss: 50437.9375 - val_mae: 50437.9375
Epoch 54/100
250/250 [==============================] - 1s 4ms/step - loss: 49501.8008 - mae: 49501.8008 - val_loss: 50434.7578 - val_mae: 50434.7578
Epoch 55/100
250/250 [==============================] - 1s 4ms/step - loss: 49491.8555 - mae: 49491.8555 - val_loss: 50438.2461 - val_mae: 50438.2461
Epoch 56/100
250/250 [==============================] - 1s 4ms/step - loss: 49487.1289 - mae: 49487.1289 - val_loss: 50441.8594 - val_mae: 50441.8594
Epoch 57/100
250/250 [==============================] - 1s 4ms/step - loss: 49485.0664 - mae: 49485.0664 - val_loss: 50439.7539 - val_mae: 50439.7539
Epoch 58/100
250/250 [==============================] - 1s 3ms/step - loss: 49479.5859 - mae: 49479.5859 - val_loss: 50434.4375 - val_mae: 50434.4375
Epoch 59/100
250/250 [==============================] - 1s 4ms/step - loss: 49471.1016 - mae: 49471.1016 - val_loss: 50434.3125 - val_mae: 50434.3125
Epoch 60/100
250/250 [==============================] - 1s 4ms/step - loss: 49468.1523 - mae: 49468.1523 - val_loss: 50423.1211 - val_mae: 50423.1211
Epoch 61/100
250/250 [==============================] - 1s 4ms/step - loss: 49460.4609 - mae: 49460.4609 - val_loss: 50435.5508 - val_mae: 50435.5508
Epoch 62/100
250/250 [==============================] - 1s 4ms/step - loss: 49457.9102 - mae: 49457.9102 - val_loss: 50434.4688 - val_mae: 50434.4688
Epoch 63/100
250/250 [==============================] - 1s 4ms/step - loss: 49452.5703 - mae: 49452.5703 - val_loss: 50419.7422 - val_mae: 50419.7422
Epoch 64/100
250/250 [==============================] - 1s 3ms/step - loss: 49448.5039 - mae: 49448.5039 - val_loss: 50428.6211 - val_mae: 50428.6211
Epoch 65/100
250/250 [==============================] - 1s 3ms/step - loss: 49443.0391 - mae: 49443.0391 - val_loss: 50421.7109 - val_mae: 50421.7109
Epoch 66/100
250/250 [==============================] - 1s 4ms/step - loss: 49440.0938 - mae: 49440.0938 - val_loss: 50427.3555 - val_mae: 50427.3555
Epoch 67/100
250/250 [==============================] - 1s 3ms/step - loss: 49434.4570 - mae: 49434.4570 - val_loss: 50421.8555 - val_mae: 50421.8555
Epoch 68/100
250/250 [==============================] - 1s 4ms/step - loss: 49427.6328 - mae: 49427.6328 - val_loss: 50436.9297 - val_mae: 50436.9297
Epoch 69/100
250/250 [==============================] - 1s 3ms/step - loss: 49425.1719 - mae: 49425.1719 - val_loss: 50427.3672 - val_mae: 50427.3672
Epoch 70/100
250/250 [==============================] - 1s 3ms/step - loss: 49425.3047 - mae: 49425.3047 - val_loss: 50427.6836 - val_mae: 50427.6836
Epoch 71/100
250/250 [==============================] - 1s 4ms/step - loss: 49415.0664 - mae: 49415.0664 - val_loss: 50425.3867 - val_mae: 50425.3867
Epoch 72/100
250/250 [==============================] - 1s 5ms/step - loss: 49412.6250 - mae: 49412.6250 - val_loss: 50413.4609 - val_mae: 50413.4609
Epoch 73/100
250/250 [==============================] - 1s 4ms/step - loss: 49410.3008 - mae: 49410.3008 - val_loss: 50417.7969 - val_mae: 50417.7969
Epoch 74/100
250/250 [==============================] - 2s 8ms/step - loss: 49401.5430 - mae: 49401.5430 - val_loss: 50432.3828 - val_mae: 50432.3828
Epoch 75/100
250/250 [==============================] - 2s 9ms/step - loss: 49401.2734 - mae: 49401.2734 - val_loss: 50416.5781 - val_mae: 50416.5781
Epoch 76/100
250/250 [==============================] - 2s 8ms/step - loss: 49395.2422 - mae: 49395.2422 - val_loss: 50426.5312 - val_mae: 50426.5312
Epoch 77/100
250/250 [==============================] - 2s 9ms/step - loss: 49392.8867 - mae: 49392.8867 - val_loss: 50423.1367 - val_mae: 50423.1367
Epoch 78/100
250/250 [==============================] - 2s 9ms/step - loss: 49392.8516 - mae: 49392.8516 - val_loss: 50430.8398 - val_mae: 50430.8398
Epoch 79/100
250/250 [==============================] - 2s 10ms/step - loss: 49388.3242 - mae: 49388.3242 - val_loss: 50431.3008 - val_mae: 50431.3008
Epoch 80/100
250/250 [==============================] - 2s 10ms/step - loss: 49381.3359 - mae: 49381.3359 - val_loss: 50437.8867 - val_mae: 50437.8867
Epoch 81/100
250/250 [==============================] - 2s 8ms/step - loss: 49378.3789 - mae: 49378.3789 - val_loss: 50449.8008 - val_mae: 50449.8008
Epoch 82/100
250/250 [==============================] - 2s 9ms/step - loss: 49376.7930 - mae: 49376.7930 - val_loss: 50454.6172 - val_mae: 50454.6172

In [47]:
%load_ext tensorboard
%tensorboard --logdir regressionlogs/fit

The tensorboard extension is already loaded. To reload it, use:
  %reload_ext tensorboard

Reusing TensorBoard on port 6006 (pid 12132), started 0:00:52 ago. (Use '!kill 12132' to kill it.)

In [48]:
test_loss, test_mae = model.evaluate(X_test, Y_test)
print(f'Test MAE: {test_mae}')

63/63 [==============================] - 0s 2ms/step - loss: 50413.4609 - mae: 50413.4609
Test MAE: 50413.4609375

In [49]:
model.save('regression_model.h5')

c:\Users\harsh\anaconda3\envs\v_env\Lib\site-packages\keras\src\engine\training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(